// Généré : source unique des lettres, utilisée par l'app et par le script d'enregistrement.
const LETTERS = [
  {n:1,f:1,id:"nun",name:"Nūn",tr:"n",sk:"dents",cx:1,dots:"1 point dessus",
   forms:{isolee:"ن",debut:"نـ",milieu:"ـنـ",fin:"ـن"},
   mouth:"Pointe de la langue contre les incisives supérieures, son nasal.",trap:null,
   word:{ar:"نَمْل",fr:"fourmis",slug:"naml"}},
  {n:2,f:1,id:"mim",name:"Mīm",tr:"m",sk:"solo",cx:1,dots:"aucun point",
   forms:{isolee:"م",debut:"مـ",milieu:"ـمـ",fin:"ـم"},
   mouth:"Lèvres fermées, son nasal.",trap:null,
   word:{ar:"مَال",fr:"bien, richesse",slug:"mal"}},
  {n:3,f:1,id:"ta",name:"Tā'",tr:"t",sk:"dents",cx:1,dots:"2 points dessus",
   forms:{isolee:"ت",debut:"تـ",milieu:"ـتـ",fin:"ـت"},
   mouth:"Pointe de la langue derrière les incisives supérieures, sec.",
   trap:"Ne pas l'aspirer comme le « t » anglais.",
   word:{ar:"تَمْر",fr:"dattes",slug:"tamr"}},
  {n:4,f:1,id:"lam",name:"Lām",tr:"l",sk:"solo",cx:1,dots:"aucun point",
   forms:{isolee:"ل",debut:"لـ",milieu:"ـلـ",fin:"ـل"},
   mouth:"Pointe de la langue au palais, l'air passe sur les côtés.",trap:null,
   word:{ar:"لَيْل",fr:"nuit",slug:"layl"}},
  {n:5,f:1,id:"alif",name:"Alif",tr:"ā",sk:"solo",cx:0,dots:"aucun point",
   forms:{isolee:"ا",fin:"ـا"},
   mouth:"Support de la voyelle longue ā. Gorge ouverte, aucun obstacle.",trap:null,
   word:{ar:"مَا",fr:"quoi / ne pas",slug:"ma"},noSyl:1},
  {n:6,f:2,id:"ya",name:"Yā'",tr:"y",sk:"dents",cx:1,dots:"2 points dessous",
   forms:{isolee:"ي",debut:"يـ",milieu:"ـيـ",fin:"ـي"},
   mouth:"Comme le « y » de yaourt. Sert aussi de voyelle longue ī.",trap:null,
   word:{ar:"يَمِين",fr:"droite",slug:"yamin"}},
  {n:7,f:2,id:"waw",name:"Wāw",tr:"w",sk:"solo",cx:0,dots:"aucun point",
   forms:{isolee:"و",fin:"ـو"},
   mouth:"Comme le « w » de watt. Sert aussi de voyelle longue ū.",
   trap:"Jamais « v ».",
   word:{ar:"هُوَ",fr:"lui",slug:"houwa"}},
  {n:8,f:2,id:"ha",name:"Hā'",tr:"h",sk:"solo",cx:1,dots:"aucun point",
   forms:{isolee:"ه",debut:"هـ",milieu:"ـهـ",fin:"ـه"},
   mouth:"Souffle expiré depuis la gorge, léger mais nettement audible.",
   trap:"Le réflexe français est d'avaler le h. Ici il doit s'entendre à chaque fois.",
   word:{ar:"هِلَال",fr:"croissant de lune",slug:"hilal"}},
  {n:9,f:2,id:"sin",name:"Sīn",tr:"s",sk:"sin",cx:1,dots:"aucun point",
   forms:{isolee:"س",debut:"سـ",milieu:"ـسـ",fin:"ـس"},
   mouth:"Sifflante fine, pointe de la langue près des incisives.",
   trap:"Toujours « ss », jamais « z » entre deux voyelles — le réflexe français (poison / poisson) va te trahir.",
   word:{ar:"سَهْل",fr:"facile",slug:"sahl"}},
  {n:10,f:2,id:"shin",name:"Shīn",tr:"sh",sk:"sin",cx:1,dots:"3 points dessus",
   forms:{isolee:"ش",debut:"شـ",milieu:"ـشـ",fin:"ـش"},
   mouth:"Comme « ch » de chat, langue plus étalée vers le palais.",trap:null,
   word:{ar:"شَمْس",fr:"soleil",slug:"shams"}},
  {n:11,f:3,id:"fa",name:"Fā'",tr:"f",sk:"faqaf",cx:1,dots:"1 point dessus",
   forms:{isolee:"ف",debut:"فـ",milieu:"ـفـ",fin:"ـف"},
   mouth:"Incisives supérieures posées sur la lèvre inférieure.",trap:null,
   word:{ar:"فَم",fr:"bouche",slug:"fam"}},
  {n:12,f:3,id:"kaf",name:"Kāf",tr:"k",sk:"solo",cx:1,dots:"aucun point",
   forms:{isolee:"ك",debut:"كـ",milieu:"ـكـ",fin:"ـك"},
   mouth:"Milieu-arrière du palais, comme le « c » de car.",
   trap:"À bien distinguer de ق, qui se forme plus en arrière.",
   word:{ar:"كِتَاب",fr:"livre",slug:"kitab"}},
  {n:13,f:3,id:"ba",name:"Bā'",tr:"b",sk:"dents",cx:1,dots:"1 point dessous",
   forms:{isolee:"ب",debut:"بـ",milieu:"ـبـ",fin:"ـب"},
   mouth:"Lèvres, comme « b ».",trap:null,
   word:{ar:"بَيْت",fr:"maison",slug:"bayt"}},
  {n:14,f:3,id:"ra",name:"Rā'",tr:"r",sk:"ra",cx:0,dots:"aucun point",
   forms:{isolee:"ر",fin:"ـر"},
   mouth:"R battu : la pointe de la langue frappe le palais UNE fois, comme le « r » espagnol ou italien.",
   trap:"PIÈGE MAJEUR. Le « r » français est grasseyé, produit dans la gorge — c'est un son totalement différent, qui correspond en fait à غ. Prononcer ر à la française revient à dire une autre lettre.",
   word:{ar:"رَجُل",fr:"homme",slug:"rajul"}},
  {n:15,f:3,id:"zay",name:"Zāy",tr:"z",sk:"ra",cx:0,dots:"1 point dessus",
   forms:{isolee:"ز",fin:"ـز"},
   mouth:"Comme « z » de zéro, sonore.",trap:null,
   word:{ar:"زَيْت",fr:"huile",slug:"zayt"}},
  {n:16,f:4,id:"dal",name:"Dāl",tr:"d",sk:"dal",cx:0,dots:"aucun point",
   forms:{isolee:"د",fin:"ـد"},
   mouth:"Pointe de la langue derrière les incisives supérieures, sonore.",trap:null,
   word:{ar:"دَرْس",fr:"leçon",slug:"dars"}},
  {n:17,f:4,id:"ayn",name:"'Ayn",tr:"ʿ",sk:"ayn",cx:1,dots:"aucun point",
   forms:{isolee:"ع",debut:"عـ",milieu:"ـعـ",fin:"ـع"},
   mouth:"Constriction au milieu de la gorge, son sonore et serré, comme une compression.",
   trap:"Totalement absent du français. Aucun équivalent : uniquement par imitation d'un modèle correct. Ne l'approxime pas en « a ».",
   word:{ar:"عَين",fr:"œil",slug:"ayn"}},
  {n:18,f:4,id:"djim",name:"Djīm",tr:"j",sk:"djim",cx:1,dots:"1 point dessous",
   forms:{isolee:"ج",debut:"جـ",milieu:"ـجـ",fin:"ـج"},
   mouth:"Comme « dj » de Djibouti : une occlusion suivie du son « j ».",
   trap:"Pas le « j » français de « jour », plus relâché.",
   word:{ar:"جَمَل",fr:"chameau",slug:"jamal"}},
  {n:19,f:4,id:"tha",name:"Thā'",tr:"th",sk:"dents",cx:1,dots:"3 points dessus",
   forms:{isolee:"ث",debut:"ثـ",milieu:"ـثـ",fin:"ـث"},
   mouth:"Langue entre les dents, souffle sourd : le « th » anglais de think.",
   trap:"Absent du français, souvent remplacé par « s » ou « t ». Les deux sont faux.",
   word:{ar:"ثَوب",fr:"vêtement",slug:"thawb"}},
  {n:20,f:4,id:"dhal",name:"Dhāl",tr:"dh",sk:"dal",cx:0,dots:"1 point dessus",
   forms:{isolee:"ذ",fin:"ـذ"},
   mouth:"Langue entre les dents, sonore : le « th » anglais de this.",
   trap:"Souvent remplacé par « z ». C'est faux — la langue doit sortir entre les dents.",
   word:{ar:"ذَهَب",fr:"or",slug:"dhahab"}},
  {n:21,f:5,id:"kha",name:"Khā'",tr:"kh",sk:"djim",cx:1,dots:"1 point dessus",
   forms:{isolee:"خ",debut:"خـ",milieu:"ـخـ",fin:"ـخ"},
   mouth:"Raclement sourd du fond du palais : la jota espagnole, ou le « ch » allemand de Bach.",
   trap:"À distinguer de ح (souffle sans raclement) et de ه (souffle plus léger).",
   word:{ar:"خُبْز",fr:"pain",slug:"khubz"}},
  {n:22,f:5,id:"hha",name:"Ḥā'",tr:"ḥ",sk:"djim",cx:1,dots:"aucun point",
   forms:{isolee:"ح",debut:"حـ",milieu:"ـحـ",fin:"ـح"},
   mouth:"Souffle du fond de la gorge, gorge ouverte et resserrée, SANS raclement.",
   trap:"Trois souffles à ne jamais confondre : ه (léger, avant), ح (gorge, ouvert), خ (raclement). Si tous sonnent pareil chez toi, aucun n'est correct.",
   word:{ar:"حَجّ",fr:"pèlerinage",slug:"hajj"}},
  {n:23,f:5,id:"sad",name:"Ṣād",tr:"ṣ",sk:"sad",cx:1,dots:"aucun point",
   forms:{isolee:"ص",debut:"صـ",milieu:"ـصـ",fin:"ـص"},
   mouth:"Emphatique : le س avec la langue épaissie et creusée, arrière relevé. Son gras et grave.",
   trap:"Doit s'entendre nettement différent de س.",
   word:{ar:"صَبْر",fr:"patience",slug:"sabr"}},
  {n:24,f:5,id:"ghayn",name:"Ghayn",tr:"gh",sk:"ayn",cx:1,dots:"1 point dessus",
   forms:{isolee:"غ",debut:"غـ",milieu:"ـغـ",fin:"ـغ"},
   mouth:"Raclement sonore du fond du palais, version sonore de خ.",
   trap:"Proche du « r » français grasseyé. C'est ton seul appui naturel — à l'inverse exact de ر.",
   word:{ar:"غَيم",fr:"nuage",slug:"ghaym"}},
  {n:25,f:5,id:"qaf",name:"Qāf",tr:"q",sk:"faqaf",cx:1,dots:"2 points dessus",
   forms:{isolee:"ق",debut:"قـ",milieu:"ـقـ",fin:"ـق"},
   mouth:"Fond du palais, occlusion sèche et profonde, plus en arrière que ك.",
   trap:"Ne pas la réduire à ك. Le point de contact est nettement plus reculé.",
   word:{ar:"قَمَر",fr:"lune",slug:"qamar"}},
  {n:26,f:6,id:"tta",name:"Ṭā'",tr:"ṭ",sk:"tta",cx:1,dots:"aucun point",
   forms:{isolee:"ط",debut:"طـ",milieu:"ـطـ",fin:"ـط"},
   mouth:"Emphatique : le ت avec la langue épaissie, son plein et grave.",
   trap:"Doit s'entendre différent de ت.",
   word:{ar:"طِفْل",fr:"enfant",slug:"tifl"}},
  {n:27,f:6,id:"dad",name:"Ḍād",tr:"ḍ",sk:"sad",cx:1,dots:"1 point dessus",
   forms:{isolee:"ض",debut:"ضـ",milieu:"ـضـ",fin:"ـض"},
   mouth:"Emphatique : le côté de la langue presse contre les molaires supérieures.",
   trap:"Réputée la plus difficile de l'alphabet. Ne pas la réduire à د ni à ظ.",
   word:{ar:"ضَوء",fr:"lumière",slug:"daw"}},
  {n:28,f:6,id:"zza",name:"Ẓhā'",tr:"ẓ",sk:"tta",cx:1,dots:"1 point dessus",
   forms:{isolee:"ظ",debut:"ظـ",milieu:"ـظـ",fin:"ـظ"},
   mouth:"Emphatique : le ذ avec la langue épaissie, sonore et grave.",
   trap:"Doit s'entendre différent de ذ et de ض.",
   word:{ar:"ظُهْر",fr:"midi",slug:"zuhr"}}
];
